name: CI/CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

permissions:
  contents: write
  issues: write
  pull-requests: write
  packages: write

jobs:
  test-and-build:
    name: Test and Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 23
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run Tests
        run: npm test

  docker-build:
    name: Build & Push Image
    needs: test-and-build
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Docker Build & Push
        uses: juninmd/base-actions/docker-build-push@main
        with:
          image-name: ${{ github.repository }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

  deploy:
    name: Deploy to ArgoCD
    needs: docker-build
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - name: ArgoCD Deploy
        uses: juninmd/base-actions/deploy-to-argocd@main
        with:
          app-name: queima-buchinho
          image-tag: latest
          charts-token: ${{ secrets.GITHUB_TOKEN }}
